#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 18080
spring:
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: redis.jtcl.top
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 6
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: 123456
    # mysql数据源
  datasource:
    url: jdbc:mysql://mysql.jtcl.top:3306/wvp2?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: jtcl.top

# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP
  ip: 172.16.6.92
  # [可选] 28181服务监听的端口
  port: 5060

#zlm 默认服务器配置
media:
  id: VjB5QBD4aYq9HBBq
  # [必须修改] zlm服务器的内网IP
  ip: 192.168.3.93
  # [必须修改] zlm服务器的http.port
  http-port: 80
  # [可选] zlm服务器的hook.admin_params=secret
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring-local.xml
